import { appLayoutConstants } from "@constants/layoutConstants";
import { CSSProperties } from "react";

export const styles = {
  cardContent: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    gap: appLayoutConstants.contentSectionGap,
  },
  heroSection: {
    position: "relative",
    width: "100%",
  },
  heroBadgeContainer: {
    position: "absolute",
    bottom: 16,
    left: 16,
    zIndex: 1,
  },
  heroBottomLeftStack: {
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    bottom: 16,
    left: 16,
    zIndex: 1,
    gap: 12,
    alignItems: "flex-start",
  },
  heroActionContainer: {
    position: "absolute",
    bottom: 16,
    right: 16,
    zIndex: 1,
  },
  heroBadge: {
    display: "flex",
    flexDirection: "column",
    paddingInline: 12,
    paddingBlock: 8,
    borderRadius: appLayoutConstants.globalCornerRadius,
    borderWidth: 1,
    borderStyle: "solid",
    alignSelf: "flex-start",
  },
  contentBody: {
    display: "flex",
    flexDirection: "column",
    gap: appLayoutConstants.contentSectionGap,
  },
  contentSection: {
    display: "flex",
    flexDirection: "column",
    gap: appLayoutConstants.contentSectionGap - 4,
  },
  stackGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  actionSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 12,
  },
  actionLinks: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 16,
  },
  actionButton: {
    minWidth: 160,
    marginInline: 0,
    height: appLayoutConstants.textInputHeight,
    borderRadius: appLayoutConstants.globalCornerRadius,
  },
  modalRoot: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1000,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.58)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingInline: appLayoutConstants.contentSectionGap,
    cursor: "auto",
  },
  modalDialog: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    boxSizing: "border-box",
    maxWidth: 560,
    padding: 32,
    borderRadius: appLayoutConstants.globalCornerRadius,
    borderWidth: 1,
    borderStyle: "solid",
    gap: appLayoutConstants.contentSectionGap,
    cursor: "auto",
  },
  modalHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  modalHeaderTop: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
  },
  modalHeaderCopy: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    gap: 8,
  },
  modalCloseButton: {
    display: "flex",
    width: 32,
    height: 32,
    boxSizing: "border-box",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "solid",
  },
  modalBody: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  modalActions: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 8,
  },
  modalActionButton: {
    flexGrow: 1,
    flexBasis: 208,
    minWidth: 208,
  },
  descriptionSection: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: appLayoutConstants.contentSectionPaddingVertical + 4,
    borderRadius: appLayoutConstants.globalCornerRadius,
    borderWidth: 1,
    borderStyle: "solid",
  },
  contextSection: {
    display: "flex",
    flexDirection: "column",
    padding: 16,
    borderRadius: appLayoutConstants.globalCornerRadius,
    borderWidth: 1,
    borderStyle: "solid",
    gap: 8,
  },
  projectContextText: {
    fontStyle: "italic",
    fontWeight: "400",
  },
  descriptionGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  bulletRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  bulletGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    paddingTop: 4,
  },
  bulletMarker: {
    minWidth: 12,
  },
  bulletText: {
    flex: 1,
  },
} satisfies Record<string, CSSProperties>;
