import {
  mdiAccount,
  mdiAlphaTCircle,
  mdiArrowBottomRightThinCircleOutline,
  mdiArrowCollapseDown,
  mdiArrowCollapseUp,
  mdiArrowExpandHorizontal,
  mdiArrowExpandVertical,
  mdiArrowLeft,
  mdiArrowLeftCircle,
  mdiArrowLeftCircleOutline,
  mdiArrowRight,
  mdiArrowRightCircle,
  mdiArrowRightCircleOutline,
  mdiArrowRightThinCircleOutline,
  mdiArrowTopRightThinCircleOutline,
  mdiBackupRestore,
  mdiBell,
  mdiBookEditOutline,
  mdiBookOpenVariantOutline,
  mdiBug,
  mdiBullhorn,
  mdiCalendar,
  mdiCamera,
  mdiCertificateOutline,
  mdiCheck,
  mdiCheckboxBlank,
  mdiCheckboxMarked,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiCircleOutline,
  mdiClipboardListOutline,
  mdiClipboardTextOutline,
  mdiClock,
  mdiClose,
  mdiCog,
  mdiCube,
  mdiDotsHorizontal,
  mdiDownload,
  mdiEmail,
  mdiEmailOutline,
  mdiExclamationThick,
  mdiFacebook,
  mdiFileCode,
  mdiFileCog,
  mdiFileExport,
  mdiFileImport,
  mdiFilePdfBox,
  mdiFileSign,
  mdiFolderMultipleImage,
  mdiFolderZip,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiHome,
  mdiImageSizeSelectSmall,
  mdiInformation,
  mdiInformationOutline,
  mdiLock,
  mdiLockOpen,
  mdiLoginVariant,
  mdiLogoutVariant,
  mdiMapMarker,
  mdiMapOutline,
  mdiMapSearch,
  mdiMenu,
  mdiOpenInNew,
  mdiPen,
  mdiPhone,
  mdiPlus,
  mdiProgressQuestion,
  mdiResizeBottomRight,
  mdiScaleBalance,
  mdiShieldAccount,
  mdiShieldLockOutline,
  mdiSortNumericDescending,
  mdiStar,
  mdiSync,
  mdiTab,
  mdiTabUnselected,
  mdiTrashCanOutline,
  mdiUpload,
  mdiWalk,
  mdiWhatsapp,
  mdiRocketLaunchOutline,
  mdiMoonWaningCrescent,
  mdiWhiteBalanceSunny,
  mdiThemeLightDark,
  mdiLinkedin,
  mdiGithub,
} from "@mdi/js";
import { CSSProperties } from "react";
import { TextStyle } from "react-native";

export const iconMap = {
  account: mdiAccount,
  "alpha-t-circle": mdiAlphaTCircle,
  "arrow-left": mdiArrowLeft,
  "arrow-left-circle": mdiArrowLeftCircle,
  "arrow-right": mdiArrowRight,
  "arrow-right-circle": mdiArrowRightCircle,
  "backup-restore": mdiBackupRestore,
  "book-edit-outline": mdiBookEditOutline,
  "book-open-variant-outline": mdiBookOpenVariantOutline,
  calendar: mdiCalendar,
  camera: mdiCamera,
  check: mdiCheck,
  "chevron-right": mdiChevronRight,
  close: mdiClose,
  cog: mdiCog,
  cube: mdiCube,
  download: mdiDownload,
  email: mdiEmail,
  "email-outline": mdiEmailOutline,
  facebook: mdiFacebook,
  "file-cog": mdiFileCog,
  "file-pdf-box": mdiFilePdfBox,
  "folder-multiple-image": mdiFolderMultipleImage,
  fullscreen: mdiFullscreen,
  "information-outline": mdiInformationOutline,
  "login-variant": mdiLoginVariant,
  "logout-variant": mdiLogoutVariant,
  "map-marker": mdiMapMarker,
  "map-outline": mdiMapOutline,
  pen: mdiPen,
  phone: mdiPhone,
  plus: mdiPlus,
  "shield-account": mdiShieldAccount,
  "trash-can-outline": mdiTrashCanOutline,
  upload: mdiUpload,
  walk: mdiWalk,
  whatsapp: mdiWhatsapp,
  home: mdiHome,
  "clipboard-list-outline": mdiClipboardListOutline,
  bell: mdiBell,
  menu: mdiMenu,
  lock: mdiLock,
  "lock-open": mdiLockOpen,
  "progress-question": mdiProgressQuestion,
  information: mdiInformation,
  star: mdiStar,
  circle: mdiCircle,
  "circle-outline": mdiCircleOutline,
  "chevron-up": mdiChevronUp,
  "exclamation-thick": mdiExclamationThick,
  "open-in-new": mdiOpenInNew,
  "arrow-expand-horizontal": mdiArrowExpandHorizontal,
  clock: mdiClock,
  "arrow-collapse-up": mdiArrowCollapseUp,
  "arrow-collapse-down": mdiArrowCollapseDown,
  "arrow-expand-vertical": mdiArrowExpandVertical,
  "arrow-top-right-thin-circle-outline": mdiArrowTopRightThinCircleOutline,
  "arrow-bottom-right-thin-circle-outline":
    mdiArrowBottomRightThinCircleOutline,
  "arrow-right-thin-circle-outline": mdiArrowRightThinCircleOutline,
  "fullscreen-exit": mdiFullscreenExit,
  "dots-horizontal": mdiDotsHorizontal,
  bullhorn: mdiBullhorn,
  "map-search": mdiMapSearch,
  "sort-numeric-descending": mdiSortNumericDescending,
  bug: mdiBug,
  "file-code": mdiFileCode,
  sync: mdiSync,
  "file-export": mdiFileExport,
  "folder-zip": mdiFolderZip,
  resize: mdiResizeBottomRight,
  tab: mdiTab,
  "tab-unselected": mdiTabUnselected,
  "image-size-select-small": mdiImageSizeSelectSmall,
  "file-import": mdiFileImport,
  "clipboard-text-outline": mdiClipboardTextOutline,
  "arrow-right-circle-outline": mdiArrowRightCircleOutline,
  "arrow-left-circle-outline": mdiArrowLeftCircleOutline,
  "checkbox-blank": mdiCheckboxBlank,
  "checkbox-marked": mdiCheckboxMarked,
  "scale-balance": mdiScaleBalance,
  "file-sign": mdiFileSign,
  "shield-lock-outline": mdiShieldLockOutline,
  "certificate-outline": mdiCertificateOutline,
  "rocket-launch-outline": mdiRocketLaunchOutline,
  "white-balance-sunny": mdiWhiteBalanceSunny,
  "moon-waning-crescent": mdiMoonWaningCrescent,
  "theme-light-dark": mdiThemeLightDark,
  linkedin: mdiLinkedin,
  github: mdiGithub,
  xing: "M18.188 2h3.542L14.09 14.042l4.733 8.168h-3.542l-4.74-8.168L18.188 2zM9.913 7.08l2.19 3.744-3.51 6.096H5.052l3.51-6.096-2.19-3.744h3.542z",
} as const;

export type WnaIconProps = {
  iconName: keyof typeof iconMap;
  size?: number;
  color?: string;
  style?: TextStyle | CSSProperties;
};
