name: ci-coverage

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v5

      - name: set up project
        uses: ./.github/actions/setup-project

      - name: coverage
        run: npm run test:coverage
