name: ci-lint-prettier

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v5

      - name: set up project
        uses: ./.github/actions/setup-project

      - name: prettier
        run: npm run test:prettier

      - name: lint
        run: npm run lint

      - name: types
        run: npm run test:types

      - name: circular dependencies
        run: npm run test:circular
