name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint_prettier:
    uses: ./.github/workflows/ci-lint-prettier.yml

  unit:
    needs: lint_prettier
    uses: ./.github/workflows/ci-unit.yml

  integration:
    needs: unit
    uses: ./.github/workflows/ci-integration.yml

  smoke:
    needs: integration
    uses: ./.github/workflows/ci-smoke.yml

  e2e:
    needs: smoke
    uses: ./.github/workflows/ci-e2e.yml
